export const LANGS = ["en", "ar"];

export const GUIDE_CONTENT = {
  en: {
    dir: "ltr",
    langLabel: "English",
    nav: {
      tour: "Quick tour",
      workflow: "Workflow map",
      concepts: "Core concepts",
      checklist: "Publishing checklist",
      manual: "Manual publishing",
      defaults: "Defaults system",
      pages: "Page-by-page map",
      routine: "Weekly routine",
      mistakes: "Common mistakes",
      faq: "FAQ",
    },
    hero: {
      eyebrow: "Learning center",
      title: "Learn JoSam Content Hub",
      subtitle:
        "Understand the workflow, prepare content faster, and publish without losing track.",
      actions: {
        tour: "Start quick tour",
        create: "Create content",
        dashboard: "Open dashboard",
      },
      tags: [
        { label: "Workflow first", tone: "neutral" },
        { label: "Manual publishing ready", tone: "accent" },
        { label: "Integrations later", tone: "soft" },
      ],
    },
    quickTour: {
      eyebrow: "Quick tour",
      title: "Five steps end to end",
      subtitle: "A mini course on how a piece of content moves through the app.",
      prev: "Previous",
      next: "Next",
      done: "What 'done' looks like",
      page: "Where you do it",
      steps: [
        {
          label: "Capture the idea",
          body:
            "Open Create Content and write the spark — title, category, and a one-line hook. Script and platforms are optional at this point.",
          page: "/content/new",
          pageLabel: "Create Content",
          done: "A new content item exists in Idea status.",
        },
        {
          label: "Prepare platform versions",
          body:
            "On the details page, switch between platform tabs and write the caption, hashtags, and per-platform copy. Apply Smart Defaults to save typing.",
          page: "/content",
          pageLabel: "Content Library",
          done: "Each target platform has a draft you would actually post.",
        },
        {
          label: "Upload media",
          body:
            "Add a thumbnail and the final video on the same details page. Media lives with the content item, not with a single platform.",
          page: "/content",
          pageLabel: "Content Library",
          done: "Thumbnail and video are visible on the content item.",
        },
        {
          label: "Schedule manually",
          body:
            "Inside the platform tab, open the Schedule section and pick a time. A reminder is created so you don't miss it.",
          page: "/calendar",
          pageLabel: "Calendar",
          done: "The post shows up on the calendar with a reminder.",
        },
        {
          label: "Publish and log",
          body:
            "When the reminder fires, post on the real platform, paste the URL back, and mark the post as Published. The publish log records it.",
          page: "/publish-logs",
          pageLabel: "Publish Logs",
          done: "Status flips to manual_done and the URL is saved.",
        },
      ],
    },
    workflow: {
      eyebrow: "Workflow map",
      title: "From idea to published",
      subtitle: "Click a status to see what it means.",
      stages: [
        {
          status: "idea",
          label: "Idea",
          meaning: "A spark you wrote down so you don't lose it.",
          action: "Add a hook and pick platforms when ready.",
          mistake: "Leaving the title vague so future-you can't find it.",
        },
        {
          status: "scripted",
          label: "Scripted",
          meaning: "The script or outline is written.",
          action: "Move toward recording or shooting.",
          mistake: "Skipping the hook — every platform needs one.",
        },
        {
          status: "recorded",
          label: "Recorded",
          meaning: "Raw footage exists.",
          action: "Edit, trim, and add captions.",
          mistake: "Recording without a thumbnail plan.",
        },
        {
          status: "edited",
          label: "Edited",
          meaning: "Final media is cut and exported.",
          action: "Upload to the content item and write captions.",
          mistake: "Not exporting platform-aware aspect ratios.",
        },
        {
          status: "ready",
          label: "Ready",
          meaning: "Every needed field is filled and validated.",
          action: "Open Schedule and pick a slot.",
          mistake: "Marking ready before validation passes.",
        },
        {
          status: "scheduled",
          label: "Scheduled",
          meaning: "A reminder is set for the publish moment.",
          action: "Wait. Use Calendar to keep an eye on it.",
          mistake: "Editing the post after scheduling without rechecking.",
        },
        {
          status: "published",
          label: "Published",
          meaning: "The post is live and the URL is recorded.",
          action: "Add the URL and move on to the next idea.",
          mistake: "Forgetting to mark manual posts as published.",
        },
      ],
    },
    concepts: {
      eyebrow: "Core concepts",
      title: "Ten things to know",
      subtitle: "Click any card to expand.",
      expand: "Show more",
      collapse: "Show less",
      example: "Example",
      where: "Where",
      cards: [
        {
          name: "Content Item",
          def: "The parent idea — title, category, status, script, notes, media.",
          example: "'How I'd architect a side-SaaS in a weekend'.",
          where: "Content Library → click any row.",
        },
        {
          name: "Platform Post",
          def: "A per-platform variant of the same content item with its own caption, hashtags, and status.",
          example: "The Instagram caption is different from the YouTube description.",
          where: "Content Details → Platform composer tabs.",
        },
        {
          name: "Media Asset",
          def: "An uploaded file (thumbnail or video) attached to a content item.",
          example: "A 1080×1920 vertical export plus a thumbnail.",
          where: "Content Details → Media section.",
        },
        {
          name: "Schedule",
          def: "A planned time to publish a specific platform post.",
          example: "Tuesday 18:00 — Instagram.",
          where: "Platform composer → Schedule accordion.",
        },
        {
          name: "Reminder",
          def: "An automatic nudge that fires at the scheduled time so you don't miss it.",
          example: "A bell appears on the dashboard at 18:00.",
          where: "Dashboard → Today's reminders / Overdue.",
        },
        {
          name: "Publish Log",
          def: "The history of every publish attempt across every platform.",
          example: "Friday's IG reel — manual_done, URL saved.",
          where: "Publish Logs page.",
        },
        {
          name: "Queue Slot",
          def: "A recurring time slot you reserve for posting — e.g. 'Tuesday 18:00'.",
          example: "Three slots per week for short-form video.",
          where: "Queue Settings page.",
        },
        {
          name: "Platform Settings",
          def: "Saved defaults per platform — title style, description template, default tags.",
          example: "Every YouTube description ends with the same channel links.",
          where: "Platform Settings page.",
        },
        {
          name: "Category Defaults",
          def: "Defaults per content category — goal, hook style, hashtags, default platforms.",
          example: "Programming videos always start with a problem statement.",
          where: "Category Defaults page.",
        },
        {
          name: "Smart Defaults",
          def: "One-click actions inside the composer that pull values from Platform Defaults.",
          example: "Fill empty fields with your saved YouTube template.",
          where: "Platform composer → Smart defaults accordion.",
        },
      ],
    },
    checklist: {
      eyebrow: "How to publish a video",
      title: "Practical checklist",
      subtitle:
        "Tick items off as you go. The state is local — nothing is saved.",
      reset: "Reset checklist",
      progress: (done, total) => `${done} of ${total} done`,
      badges: {
        required: "Required",
        optional: "Optional",
        later: "Later",
      },
      items: [
        {
          label: "Create the content item",
          hint: "Title + category are enough.",
          link: "/content/new",
          linkLabel: "Open Create",
          badge: "required",
        },
        {
          label: "Pick a category",
          hint: "Drives default platforms and guidance.",
          badge: "required",
        },
        {
          label: "Add the hook",
          hint: "One sharp line that earns the watch.",
          badge: "required",
        },
        {
          label: "Add the script and notes",
          hint: "Rough is fine — refine later.",
          badge: "optional",
        },
        {
          label: "Select target platforms",
          hint: "Each one becomes its own draft.",
          badge: "required",
        },
        {
          label: "Upload thumbnail and video",
          hint: "Media is stored on the content item.",
          link: "/content",
          linkLabel: "Library",
          badge: "required",
        },
        {
          label: "Open the platform composer",
          hint: "Switch tabs to write per-platform copy.",
          badge: "required",
        },
        {
          label: "Write captions and tags",
          hint: "Different rules per platform — don't copy/paste blindly.",
          badge: "required",
        },
        {
          label: "Apply Smart Defaults",
          hint: "Fill empty fields from saved templates.",
          badge: "optional",
        },
        {
          label: "Validate the version",
          hint: "Catches missing required fields before scheduling.",
          badge: "required",
        },
        {
          label: "Schedule the post",
          hint: "Pick a time and timezone.",
          link: "/calendar",
          linkLabel: "Calendar",
          badge: "required",
        },
        {
          label: "Wait for the reminder",
          hint: "It fires on the dashboard at the scheduled time.",
          link: "/reminders",
          linkLabel: "Reminders",
          badge: "later",
        },
        {
          label: "Publish on the real platform",
          hint: "Open the IG/TikTok/FB app and post manually.",
          badge: "required",
        },
        {
          label: "Paste the URL back",
          hint: "Into the Platform post URL field.",
          badge: "required",
        },
        {
          label: "Mark the post as Published",
          hint: "Status becomes manual_done.",
          badge: "required",
        },
        {
          label: "Check publish logs",
          hint: "Your real publishing history.",
          link: "/publish-logs",
          linkLabel: "Publish Logs",
          badge: "later",
        },
      ],
    },
    manual: {
      eyebrow: "Manual publishing",
      title: "How publishing actually works",
      subtitle:
        "TikTok, Instagram, and Facebook are manual for now. The app prepares everything; you tap publish on the real platform.",
      steps: [
        {
          label: "Prepare",
          body: "Write captions, upload media, validate the version.",
        },
        {
          label: "Reminder",
          body: "At the scheduled time, a reminder fires on the dashboard.",
        },
        {
          label: "Publish manually",
          body: "Open the platform app and post. The app does not auto-publish.",
        },
        {
          label: "Mark done",
          body: "Paste the URL back and mark the post as Published.",
        },
      ],
      why: {
        title: "Why manual?",
        body:
          "Official APIs have heavy restrictions and account-safety risks. Manual publishing keeps your accounts safe and gives you final control. Automation can be added later when the APIs are stable for our use case.",
      },
    },
    defaults: {
      eyebrow: "Defaults system",
      title: "Three layers of defaults",
      subtitle: "Saves typing, keeps style consistent.",
      warning:
        "Overwrite replaces existing text. Use it only when you mean it.",
      tabs: [
        {
          key: "platform",
          label: "Platform Defaults",
          body: "Per-platform saved values: title template, description, default tags, hashtags.",
          bullets: [
            "Live under Platform Settings.",
            "Used by Smart Defaults in the composer.",
            "Edit once, reuse on every new post.",
          ],
          link: "/platforms",
          linkLabel: "Open Platform Settings",
        },
        {
          key: "category",
          label: "Category Defaults",
          body: "Per-category guidance: goal, hook style, caption style, default hashtags, default platforms.",
          bullets: [
            "Live under Category Defaults.",
            "Shown as guidance in Create Content and the composer.",
            "Default platforms auto-fill on new content if you haven't picked any.",
          ],
          link: "/category-defaults",
          linkLabel: "Open Category Defaults",
        },
        {
          key: "smart",
          label: "Smart Defaults",
          body: "One-click actions inside the platform composer.",
          bullets: [
            "Fill empty fields — adds defaults only where blank.",
            "Overwrite with defaults — replaces existing text.",
            "Use category hashtags — adds hashtags from category.",
            "Replace hashtags — overwrites current hashtags from category.",
          ],
        },
      ],
    },
    pages: {
      eyebrow: "Page-by-page map",
      title: "What each page is for",
      subtitle: "Short tour of the workspace.",
      open: "Open page",
      cards: [
        {
          name: "Dashboard",
          purpose: "Today's reminders, overdue, and what needs attention.",
          when: "Open it first thing every day.",
          link: "/dashboard",
        },
        {
          name: "Workflow",
          purpose: "Kanban-style view of where every piece is.",
          when: "When you want to see what's stuck.",
          link: "/workflow",
        },
        {
          name: "Content Library",
          purpose: "Searchable list of every content item.",
          when: "When you know what you're looking for.",
          link: "/content",
        },
        {
          name: "Create Content",
          purpose: "Quick capture for a new idea.",
          when: "Whenever a spark hits — capture before you forget.",
          link: "/content/new",
        },
        {
          name: "Content Details",
          purpose: "Edit fields, manage media, and write platform copy.",
          when: "Most of your real work happens here.",
          link: "/content",
        },
        {
          name: "Calendar",
          purpose: "Visual view of upcoming scheduled posts.",
          when: "To pick a posting time or spot gaps.",
          link: "/calendar",
        },
        {
          name: "Reminders",
          purpose: "Active and overdue reminders in one place.",
          when: "When the dashboard reminder list grows long.",
          link: "/reminders",
        },
        {
          name: "Queue Settings",
          purpose: "Recurring time slots for posting.",
          when: "To enforce a steady cadence.",
          link: "/queue",
        },
        {
          name: "Platform Settings",
          purpose: "Default title/caption/tags per platform.",
          when: "Once, when you set up the studio.",
          link: "/platforms",
        },
        {
          name: "Category Defaults",
          purpose: "Goal, hook style, hashtags, and default platforms per category.",
          when: "Once per category, then occasionally to refine.",
          link: "/category-defaults",
        },
        {
          name: "Publish Logs",
          purpose: "Every publish attempt — your real history.",
          when: "When debugging or reviewing what shipped.",
          link: "/publish-logs",
        },
      ],
    },
    routine: {
      eyebrow: "Weekly routine",
      title: "A calm weekly rhythm",
      subtitle:
        "One way to use the studio. Adapt it — but keep capture and review on the calendar.",
      days: [
        { day: "Monday", focus: "Capture ideas", body: "Open Create Content. Title + category. Don't polish yet." },
        { day: "Tuesday", focus: "Write hooks and scripts", body: "Open each idea, write a hook, sketch the script." },
        { day: "Wednesday", focus: "Record or shoot", body: "Batch your recordings — same setup, multiple pieces." },
        { day: "Thursday", focus: "Edit and upload media", body: "Cut, export, upload thumbnail and video." },
        { day: "Friday", focus: "Write captions and validate", body: "Apply Smart Defaults. Validate. Mark Ready." },
        { day: "Saturday", focus: "Schedule next week", body: "Pick times, set reminders, fill the calendar." },
        { day: "Sunday", focus: "Review publish logs", body: "What went out, what failed, what to repeat." },
      ],
    },
    mistakes: {
      eyebrow: "Common mistakes",
      title: "Do this, not that",
      subtitle: "Patterns to repeat — and ones to avoid.",
      dos: [
        { label: "Do use category defaults for faster setup.", hint: "Less typing, more shipping." },
        { label: "Do check the dashboard every day.", hint: "Overdue reminders pile up fast." },
        { label: "Do use Publish Logs as your real history.", hint: "It's the source of truth." },
        { label: "Do validate before scheduling.", hint: "Catches gaps cheaply." },
        { label: "Do mark manual posts as Published immediately after posting.", hint: "Otherwise the log lies." },
      ],
      donts: [
        { label: "Don't schedule before writing captions.", hint: "You'll forget what you meant." },
        { label: "Don't forget to upload media.", hint: "A ready post without media is not ready." },
        { label: "Don't overwrite defaults without checking.", hint: "Overwrite means replace." },
        { label: "Don't remove the uploads volume in staging.", hint: "Media will vanish." },
        { label: "Don't expect auto-publish.", hint: "You still tap publish on the real platform." },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "Things people ask",
      items: [
        {
          q: "Is this auto-publishing?",
          a: "No. The app prepares everything; you still publish on the real platform.",
        },
        {
          q: "Why do I still publish manually?",
          a: "Official APIs are restrictive and risky for account safety. Manual publishing protects accounts and keeps final control with you.",
        },
        {
          q: "Where do my videos live?",
          a: "Media assets are stored on the content item, attached via the Media section of Content Details.",
        },
        {
          q: "What is a Content Item?",
          a: "The parent idea — title, category, hook, script, notes, status, and attached media. Each platform variant lives under it.",
        },
        {
          q: "What is a Platform Post?",
          a: "A platform-specific draft (YouTube / Instagram / Facebook / TikTok) with its own caption, hashtags, URL, and status.",
        },
        {
          q: "What happens after I schedule?",
          a: "A reminder is created. At the scheduled time, the dashboard surfaces it under Today's reminders.",
        },
        {
          q: "What does manual_done mean?",
          a: "You published on the real platform and marked the post as Published, including its URL. It now counts as live in your logs.",
        },
        {
          q: "Platform Defaults vs Category Defaults?",
          a: "Platform Defaults are per-platform templates (e.g. YouTube description). Category Defaults are per-category direction (goal, hook style, default platforms).",
        },
        {
          q: "Will YouTube become automatic later?",
          a: "Possibly. The data model is ready for it. The decision depends on API stability and whether it's worth the risk versus manual control.",
        },
        {
          q: "Will TikTok become automatic later?",
          a: "Unlikely soon. TikTok's API is the most restrictive and risky for account safety. Manual will stay the default.",
        },
        {
          q: "What should I do every day?",
          a: "Open the dashboard, clear overdue reminders, write or schedule one piece, mark anything live as Published.",
        },
      ],
    },
  },

  ar: {
    dir: "rtl",
    langLabel: "العربية",
    nav: {
      tour: "جولة سريعة",
      workflow: "خريطة المسار",
      concepts: "المفاهيم الأساسية",
      checklist: "قائمة النشر",
      manual: "النشر اليدوي",
      defaults: "نظام الإعدادات الافتراضية",
      pages: "خريطة الصفحات",
      routine: "روتين أسبوعي",
      mistakes: "أخطاء شائعة",
      faq: "أسئلة شائعة",
    },
    hero: {
      eyebrow: "مركز التعلّم",
      title: "تعلّم JoSam Content Hub",
      subtitle:
        "افهم سير العمل، جهّز المحتوى أسرع، وانشر دون أن يضيع شيء بين يديك.",
      actions: {
        tour: "ابدأ الجولة السريعة",
        create: "إنشاء محتوى",
        dashboard: "فتح لوحة التحكم",
      },
      tags: [
        { label: "سير العمل أولًا", tone: "neutral" },
        { label: "النشر اليدوي جاهز", tone: "accent" },
        { label: "التكاملات لاحقًا", tone: "soft" },
      ],
    },
    quickTour: {
      eyebrow: "جولة سريعة",
      title: "خمس خطوات من الفكرة إلى النشر",
      subtitle: "ملخص مختصر لكيفية انتقال أي محتوى داخل التطبيق.",
      prev: "السابق",
      next: "التالي",
      done: "كيف تعرف أنك انتهيت",
      page: "أين تنفّذ ذلك",
      steps: [
        {
          label: "التقاط الفكرة",
          body:
            "افتح صفحة إنشاء المحتوى واكتب الفكرة سريعًا — عنوان، تصنيف، وسطر افتتاحي. النص الكامل والمنصات اختياريان الآن.",
          page: "/content/new",
          pageLabel: "إنشاء محتوى",
          done: "أصبح لديك محتوى جديد بحالة فكرة.",
        },
        {
          label: "تجهيز نسخ المنصات",
          body:
            "من صفحة التفاصيل، انتقل بين تبويبات المنصات واكتب الكابشن والهاشتاجز ونص كل منصة. استخدم الإعدادات الذكية لتوفير الوقت.",
          page: "/content",
          pageLabel: "مكتبة المحتوى",
          done: "كل منصة لديها مسودة جاهزة فعليًا للنشر.",
        },
        {
          label: "رفع الوسائط",
          body:
            "ارفع الصورة المصغّرة والفيديو النهائي من نفس صفحة التفاصيل. الوسائط مرتبطة بالمحتوى نفسه، لا بمنصة واحدة.",
          page: "/content",
          pageLabel: "مكتبة المحتوى",
          done: "الصورة المصغّرة والفيديو ظاهران على المحتوى.",
        },
        {
          label: "جدولة يدوية",
          body:
            "افتح قسم الجدولة داخل تبويب المنصة واختر الموعد. سيُنشأ تذكير حتى لا تنسى.",
          page: "/calendar",
          pageLabel: "التقويم",
          done: "ظهر المنشور في التقويم مع تذكير.",
        },
        {
          label: "النشر والتسجيل",
          body:
            "عند وقت التذكير، انشر يدويًا على المنصة، ثم الصق الرابط هنا، وضع الحالة منشور. سيُسجَّل ذلك في سجل النشر.",
          page: "/publish-logs",
          pageLabel: "سجل النشر",
          done: "تحوّلت الحالة إلى منشور يدويًا والرابط محفوظ.",
        },
      ],
    },
    workflow: {
      eyebrow: "خريطة المسار",
      title: "من الفكرة إلى النشر",
      subtitle: "اضغط على أي حالة لمعرفة معناها.",
      stages: [
        {
          status: "idea",
          label: "فكرة",
          meaning: "شرارة دوّنتها حتى لا تضيع.",
          action: "أضف السطر الافتتاحي واختر المنصات عند الجاهزية.",
          mistake: "ترك العنوان غامضًا فيصعب إيجاده لاحقًا.",
        },
        {
          status: "scripted",
          label: "مكتوب",
          meaning: "النص أو المخطط جاهز.",
          action: "انتقل إلى التسجيل أو التصوير.",
          mistake: "تجاهل السطر الافتتاحي — كل منصة تحتاجه.",
        },
        {
          status: "recorded",
          label: "مُسجَّل",
          meaning: "الفيديو الخام موجود.",
          action: "ابدأ المونتاج وأضف الترجمة.",
          mistake: "التسجيل دون فكرة عن الصورة المصغّرة.",
        },
        {
          status: "edited",
          label: "مُنتَج",
          meaning: "الفيديو النهائي جاهز ومُصدَّر.",
          action: "ارفعه على المحتوى واكتب الكابشن.",
          mistake: "تصدير بمقاسات لا تناسب المنصات.",
        },
        {
          status: "ready",
          label: "جاهز",
          meaning: "كل الحقول المطلوبة مكتملة وتجاوزت التحقق.",
          action: "افتح الجدولة واختر موعدًا.",
          mistake: "تعليم \"جاهز\" قبل أن يمر التحقق.",
        },
        {
          status: "scheduled",
          label: "مجدول",
          meaning: "هناك تذكير معدّ لوقت النشر.",
          action: "انتظر، وراقب من التقويم.",
          mistake: "التعديل بعد الجدولة دون إعادة التحقق.",
        },
        {
          status: "published",
          label: "منشور",
          meaning: "تم النشر فعليًا وسُجِّل الرابط.",
          action: "احفظ الرابط وانتقل إلى الفكرة التالية.",
          mistake: "نسيان تعليم المنشورات اليدوية كمنشورة.",
        },
      ],
    },
    concepts: {
      eyebrow: "المفاهيم الأساسية",
      title: "عشرة مفاهيم يجب فهمها",
      subtitle: "اضغط أي بطاقة لعرض التفاصيل.",
      expand: "عرض المزيد",
      collapse: "إخفاء",
      example: "مثال",
      where: "أين تجده",
      cards: [
        {
          name: "المحتوى (Content Item)",
          def: "الفكرة الأم — عنوان، تصنيف، حالة، نص، ملاحظات، ووسائط.",
          example: "\"كيف أُصمّم تطبيقًا جانبيًا في عطلة الأسبوع\".",
          where: "مكتبة المحتوى ← اضغط أي عنصر.",
        },
        {
          name: "منشور المنصة (Platform Post)",
          def: "نسخة لكل منصة من نفس المحتوى، بكابشن وهاشتاجز وحالة مستقلة.",
          example: "كابشن إنستجرام يختلف عن وصف يوتيوب.",
          where: "تفاصيل المحتوى ← تبويبات المنصات.",
        },
        {
          name: "ملف الوسائط (Media Asset)",
          def: "ملف مرفوع (صورة مصغّرة أو فيديو) مرتبط بالمحتوى.",
          example: "فيديو رأسي 1080×1920 مع صورة مصغّرة.",
          where: "تفاصيل المحتوى ← قسم الوسائط.",
        },
        {
          name: "الجدولة (Schedule)",
          def: "موعد محدد لنشر منشور منصة بعينه.",
          example: "الثلاثاء 18:00 — إنستجرام.",
          where: "محرّر المنصة ← قسم الجدولة.",
        },
        {
          name: "التذكير (Reminder)",
          def: "تنبيه تلقائي يصلك عند وقت النشر حتى لا تنسى.",
          example: "يظهر جرس على لوحة التحكم الساعة 18:00.",
          where: "لوحة التحكم ← تذكيرات اليوم/المتأخرة.",
        },
        {
          name: "سجل النشر (Publish Log)",
          def: "سجل كل محاولة نشر عبر كل المنصات.",
          example: "ريل الجمعة على إنستجرام — منشور يدويًا، الرابط محفوظ.",
          where: "صفحة سجل النشر.",
        },
        {
          name: "خانة الطابور (Queue Slot)",
          def: "موعد متكرر تحجزه للنشر، مثل: الثلاثاء 18:00.",
          example: "ثلاث خانات أسبوعيًا للفيديو القصير.",
          where: "صفحة إعدادات الطابور.",
        },
        {
          name: "إعدادات المنصة",
          def: "قيم افتراضية لكل منصة: نمط العنوان، الوصف، الوسوم.",
          example: "كل وصف يوتيوب ينتهي بنفس روابط القناة.",
          where: "صفحة إعدادات المنصات.",
        },
        {
          name: "الإعدادات الافتراضية للتصنيف",
          def: "توجيه لكل تصنيف: الهدف، نمط الافتتاح، الهاشتاجز، المنصات الافتراضية.",
          example: "فيديوهات البرمجة تبدأ دائمًا بطرح المشكلة.",
          where: "صفحة الإعدادات الافتراضية للتصنيفات.",
        },
        {
          name: "الإعدادات الذكية",
          def: "أزرار سريعة داخل المحرّر تسحب القيم من إعدادات المنصة.",
          example: "املأ الحقول الفارغة من قالب يوتيوب المحفوظ.",
          where: "محرّر المنصة ← قسم الإعدادات الذكية.",
        },
      ],
    },
    checklist: {
      eyebrow: "كيف تنشر فيديو",
      title: "قائمة عملية",
      subtitle: "ضع علامة على ما أنجزته. الحالة محلية فقط ولا تُحفظ.",
      reset: "إعادة الضبط",
      progress: (done, total) => `${done} من ${total}`,
      badges: {
        required: "مطلوب",
        optional: "اختياري",
        later: "لاحقًا",
      },
      items: [
        { label: "إنشاء المحتوى", hint: "عنوان وتصنيف يكفيان.", link: "/content/new", linkLabel: "صفحة الإنشاء", badge: "required" },
        { label: "اختيار التصنيف", hint: "يحدد المنصات الافتراضية والتوجيه.", badge: "required" },
        { label: "كتابة السطر الافتتاحي", hint: "جملة واحدة قوية تستحق المشاهدة.", badge: "required" },
        { label: "إضافة النص والملاحظات", hint: "مسودة سريعة، تُصقل لاحقًا.", badge: "optional" },
        { label: "تحديد المنصات المستهدفة", hint: "كل منصة تصبح مسودة خاصة بها.", badge: "required" },
        { label: "رفع الصورة المصغّرة والفيديو", hint: "الوسائط على المحتوى نفسه.", link: "/content", linkLabel: "المكتبة", badge: "required" },
        { label: "فتح محرّر المنصة", hint: "انتقل بين التبويبات لكتابة كل نسخة.", badge: "required" },
        { label: "كتابة الكابشن والوسوم", hint: "قواعد كل منصة مختلفة — لا تنسخ كما هو.", badge: "required" },
        { label: "تطبيق الإعدادات الذكية", hint: "املأ الحقول الفارغة من القوالب.", badge: "optional" },
        { label: "التحقق من النسخة", hint: "يكشف النقص قبل الجدولة.", badge: "required" },
        { label: "جدولة النشر", hint: "اختر موعدًا والمنطقة الزمنية.", link: "/calendar", linkLabel: "التقويم", badge: "required" },
        { label: "انتظار التذكير", hint: "يظهر على لوحة التحكم في وقت النشر.", link: "/reminders", linkLabel: "التذكيرات", badge: "later" },
        { label: "النشر على المنصة فعليًا", hint: "افتح تطبيق المنصة وانشر يدويًا.", badge: "required" },
        { label: "لصق الرابط", hint: "في حقل رابط منشور المنصة.", badge: "required" },
        { label: "تعليم المنشور كمنشور", hint: "تتحول الحالة إلى منشور يدويًا.", badge: "required" },
        { label: "مراجعة سجل النشر", hint: "هذا سجلك الحقيقي.", link: "/publish-logs", linkLabel: "سجل النشر", badge: "later" },
      ],
    },
    manual: {
      eyebrow: "النشر اليدوي",
      title: "كيف يحدث النشر فعليًا",
      subtitle:
        "تيك توك وإنستجرام وفيسبوك يدوية حاليًا. التطبيق يُجهّز كل شيء، وأنت من ينشر فعليًا.",
      steps: [
        { label: "التجهيز", body: "اكتب الكابشن، ارفع الوسائط، وتحقق من النسخة." },
        { label: "التذكير", body: "في وقت النشر يظهر تذكير على لوحة التحكم." },
        { label: "نشر يدوي", body: "افتح تطبيق المنصة وانشر — لا نشر تلقائي." },
        { label: "تعليم كمنشور", body: "الصق الرابط، وعلّم المنشور كمنشور." },
      ],
      why: {
        title: "لماذا يدوي؟",
        body:
          "واجهات النشر الرسمية مقيدة وتُشكّل خطرًا على الحسابات. النشر اليدوي يحمي حساباتك ويُبقي قرار النشر بيدك. يمكن إضافة الأتمتة لاحقًا عندما تستقر الواجهات وتناسب احتياجاتنا.",
      },
    },
    defaults: {
      eyebrow: "نظام الإعدادات الافتراضية",
      title: "ثلاث طبقات من الإعدادات",
      subtitle: "توفّر الكتابة وتُحافظ على الأسلوب.",
      warning: "الاستبدال يمحو النص الحالي. استخدمه فقط عندما تقصده فعلًا.",
      tabs: [
        {
          key: "platform",
          label: "إعدادات المنصة",
          body: "قيم محفوظة لكل منصة: قالب العنوان، الوصف، الوسوم، الهاشتاجز.",
          bullets: [
            "تجدها داخل صفحة إعدادات المنصات.",
            "تستخدمها الإعدادات الذكية في المحرّر.",
            "اضبطها مرة، وأعد استخدامها في كل منشور.",
          ],
          link: "/platforms",
          linkLabel: "فتح إعدادات المنصات",
        },
        {
          key: "category",
          label: "إعدادات التصنيف",
          body: "توجيه لكل تصنيف: الهدف، نمط الافتتاح، نمط الكابشن، الهاشتاجز، المنصات الافتراضية.",
          bullets: [
            "تجدها داخل صفحة الإعدادات الافتراضية للتصنيفات.",
            "تظهر كتوجيه في إنشاء المحتوى وفي المحرّر.",
            "المنصات الافتراضية تُضاف تلقائيًا للمحتوى الجديد إن لم تختر منصات.",
          ],
          link: "/category-defaults",
          linkLabel: "فتح إعدادات التصنيف",
        },
        {
          key: "smart",
          label: "الإعدادات الذكية",
          body: "أزرار سريعة داخل محرّر المنصة.",
          bullets: [
            "املأ الحقول الفارغة — تضيف الافتراضيات حيث لا يوجد نص.",
            "استبدل بالافتراضيات — تمحو وتستبدل بالكامل.",
            "استخدم هاشتاجز التصنيف — تُضافها لقائمتك.",
            "استبدل الهاشتاجز — تستبدل الهاشتاجز الحالية بهاشتاجز التصنيف.",
          ],
        },
      ],
    },
    pages: {
      eyebrow: "خريطة الصفحات",
      title: "وظيفة كل صفحة",
      subtitle: "جولة قصيرة في مساحة العمل.",
      open: "فتح الصفحة",
      cards: [
        { name: "لوحة التحكم", purpose: "تذكيرات اليوم والمتأخرة وما يحتاج اهتمامك.", when: "افتحها أول شيء كل يوم.", link: "/dashboard" },
        { name: "سير العمل", purpose: "عرض كانبان لمواقع كل قطعة محتوى.", when: "حين تريد رؤية ما توقّف.", link: "/workflow" },
        { name: "مكتبة المحتوى", purpose: "قائمة قابلة للبحث لكل المحتوى.", when: "حين تعرف ما تبحث عنه.", link: "/content" },
        { name: "إنشاء محتوى", purpose: "التقاط سريع لفكرة جديدة.", when: "كلما خطرت فكرة — سجّلها قبل أن تنسى.", link: "/content/new" },
        { name: "تفاصيل المحتوى", purpose: "تعديل الحقول، إدارة الوسائط، وكتابة نص المنصات.", when: "معظم العمل الفعلي يحدث هنا.", link: "/content" },
        { name: "التقويم", purpose: "رؤية بصرية للمنشورات المجدولة.", when: "لاختيار موعد أو رصد الفجوات.", link: "/calendar" },
        { name: "التذكيرات", purpose: "تذكيرات نشطة ومتأخرة في مكان واحد.", when: "حين تطول قائمة التذكيرات على لوحة التحكم.", link: "/reminders" },
        { name: "إعدادات الطابور", purpose: "خانات نشر متكررة.", when: "لفرض إيقاع ثابت.", link: "/queue" },
        { name: "إعدادات المنصات", purpose: "قوالب العنوان والكابشن والوسوم لكل منصة.", when: "مرة عند تجهيز الاستوديو.", link: "/platforms" },
        { name: "الإعدادات الافتراضية للتصنيفات", purpose: "الهدف والافتتاح والهاشتاجز والمنصات لكل تصنيف.", when: "مرة لكل تصنيف، ثم بين فترة وأخرى للضبط.", link: "/category-defaults" },
        { name: "سجل النشر", purpose: "كل محاولات النشر — سجلك الحقيقي.", when: "عند المراجعة أو حل المشكلات.", link: "/publish-logs" },
      ],
    },
    routine: {
      eyebrow: "روتين أسبوعي",
      title: "إيقاع أسبوعي هادئ",
      subtitle:
        "هذا اقتراح للاستخدام. عدّله كما يناسبك، مع الحفاظ على الالتقاط والمراجعة في التقويم.",
      days: [
        { day: "الإثنين", focus: "التقاط الأفكار", body: "افتح إنشاء المحتوى. عنوان وتصنيف. دون تلميع." },
        { day: "الثلاثاء", focus: "كتابة السطر الافتتاحي والنص", body: "افتح كل فكرة، اكتب الافتتاحية، خطّط النص." },
        { day: "الأربعاء", focus: "التسجيل أو التصوير", body: "صوّر دفعة واحدة — نفس الإعداد، عدة قطع." },
        { day: "الخميس", focus: "المونتاج ورفع الوسائط", body: "قص، صدّر، ارفع الصورة والفيديو." },
        { day: "الجمعة", focus: "كتابة الكابشن والتحقق", body: "طبّق الإعدادات الذكية، تحقق، وضع الحالة جاهز." },
        { day: "السبت", focus: "جدولة الأسبوع القادم", body: "اختر مواعيد، اضبط التذكيرات، املأ التقويم." },
        { day: "الأحد", focus: "مراجعة سجل النشر", body: "ماذا نُشر، ماذا فشل، وماذا تكرّر." },
      ],
    },
    mistakes: {
      eyebrow: "أخطاء شائعة",
      title: "افعل هذا لا ذاك",
      subtitle: "عادات نافعة وأخرى ينبغي تجنبها.",
      dos: [
        { label: "استخدم إعدادات التصنيف لتسريع الإعداد.", hint: "كتابة أقل، نشر أكثر." },
        { label: "افتح لوحة التحكم كل يوم.", hint: "التذكيرات المتأخرة تتراكم سريعًا." },
        { label: "اعتمد سجل النشر كسجل حقيقي.", hint: "هو مصدر الحقيقة." },
        { label: "تحقق قبل الجدولة.", hint: "أرخص طريقة لكشف النواقص." },
        { label: "علّم المنشورات اليدوية فور نشرها.", hint: "وإلا سيكذب السجل." },
      ],
      donts: [
        { label: "لا تجدول قبل كتابة الكابشن.", hint: "ستنسى ما قصدته." },
        { label: "لا تنسَ رفع الوسائط.", hint: "بدون وسائط ليس جاهزًا." },
        { label: "لا تستبدل الإعدادات دون مراجعة.", hint: "الاستبدال يعني المحو." },
        { label: "لا تحذف مجلد الرفع في بيئة التجربة.", hint: "ستضيع الوسائط." },
        { label: "لا تتوقع نشرًا تلقائيًا.", hint: "النشر الفعلي يتم منك يدويًا." },
      ],
    },
    faq: {
      eyebrow: "أسئلة شائعة",
      title: "أكثر ما يُسأل",
      items: [
        { q: "هل يقوم النظام بالنشر تلقائيًا؟", a: "لا. النظام يجهّز كل شيء، لكن النشر الفعلي يتم منك." },
        { q: "لماذا أنشر يدويًا؟", a: "واجهات النشر الرسمية مقيدة وقد تُعرّض الحساب للخطر. النشر اليدوي يحمي الحسابات ويُبقي القرار بيدك." },
        { q: "أين تُحفظ الفيديوهات؟", a: "ملفات الوسائط مرفقة بالمحتوى من قسم الوسائط في صفحة التفاصيل." },
        { q: "ما هو المحتوى (Content Item)؟", a: "الفكرة الأم — عنوان، تصنيف، افتتاحية، نص، ملاحظات، حالة، ووسائط. منشورات المنصات تتفرع منه." },
        { q: "ما هو منشور المنصة؟", a: "مسودة لكل منصة (يوتيوب/إنستجرام/فيسبوك/تيك توك) لها كابشن وهاشتاجز ورابط وحالة مستقلة." },
        { q: "ماذا يحدث بعد الجدولة؟", a: "يُنشأ تذكير، ويظهر على لوحة التحكم في وقت النشر." },
        { q: "ما معنى manual_done؟", a: "يعني أنك نشرت فعليًا على المنصة وعلّمت المنشور كمنشور مع رابطه." },
        { q: "ما الفرق بين إعدادات المنصة وإعدادات التصنيف؟", a: "إعدادات المنصة قوالب لكل منصة (مثل وصف يوتيوب). إعدادات التصنيف توجيه لكل تصنيف (الهدف، الافتتاح، المنصات الافتراضية)." },
        { q: "هل يصبح يوتيوب تلقائيًا لاحقًا؟", a: "ربما. البنية مهيّأة لذلك. يعتمد القرار على استقرار الواجهة وما إذا كانت تستحق المخاطرة مقابل التحكم اليدوي." },
        { q: "هل يصبح تيك توك تلقائيًا لاحقًا؟", a: "غالبًا لا قريبًا. واجهة تيك توك هي الأكثر تقييدًا وخطرًا على الحساب. سيظل اليدوي هو الأصل." },
        { q: "ماذا أفعل كل يوم؟", a: "افتح لوحة التحكم، أنهِ التذكيرات المتأخرة، اكتب أو جدول قطعة واحدة، وعلّم ما نُشر منها." },
      ],
    },
  },
};
